---
- name: Ensure artifactory status archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_status_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure artifactory downloads archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_downloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure artifactory tempdownloads archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_tempdownloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Install homebrew
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew

- name: Add required packages
  community.general.homebrew:
    name: "{{ required_packages }}"
    state: present

- name: Get and expand archives
  ansible.builtin.include_tasks: expand_archive_posix.yml
  loop: "{{ archive_definitions }}"
  loop_control:
    loop_var: archive
