---
- name: Ensure artifactory status archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_status_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure artifactory downloads archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_downloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure artifactory tempdownloads archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_tempdownloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Insall Homebrew + required packages
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    # This is overwritten by our group_vars (cpp.build-machines)
    homebrew_installed_packages:
      - "{{ required_packages }}"
  when: not cpp_buildmachine

- name: Get and expand archives
  ansible.builtin.include_tasks: expand_archive_posix.yml
  loop: "{{ archive_definitions }}"
  loop_control:
    loop_var: archive
