---
- name: Ensure artifactory-archives directory is there
  win_file:
    path: D:\\artifactory-archives\\
    state: directory

- name: Ensure destination directory is there
  win_file:
    path: "{{ archive.base_destination_directory }}"
    state: directory

- name: Check archiveextracted file is present
  win_stat:
    path: "D:\\artifactory-archives\\{{ archive.filename }}.archiveextracted"
  register: archiveextracted

- name: Read sha256 from archiveextracted file if present
  slurp:
    src: "D:\\artifactory-archives\\{{ archive.filename }}.archiveextracted"
  register: archiveextracted_sha256
  when: archiveextracted.stat.exists

- name: Perform a HEAD on the remote file to read sha256
  win_uri:
    url: "https://artifactory.ccdc.cam.ac.uk/{{ archive.artifactory_path }}/{{ archive.filename }}"
    method: HEAD
  register: remote_archive_head

- name: Download file if sha256 changed 
  win_get_url:
    url: "https://artifactory.ccdc.cam.ac.uk/{{ archive.artifactory_path }}/{{ archive.filename }}"
    dest: "D:\\artifactory-archives\\{{ archive.filename }}"
    force: no
  when: not archiveextracted.stat.exists or remote_archive_head.x_checksum_sha256 not in archiveextracted_sha256.content|b64decode
  register: download

- name: Extract archive if sha256 changed 
  win_shell: 7za x -aoa -mmt "D:\\artifactory-archives\\{{ archive.filename }}" -o"{{ archive.base_destination_directory }}"
  when: not archiveextracted.stat.exists or remote_archive_head.x_checksum_sha256 not in archiveextracted_sha256.content|b64decode
  register: extract_command_status

- name: Move out of base directory source 
  win_shell: Get-ChildItem -Path "{{ archive.base_destination_directory }}\{{ archive.move_and_delete_base_directory }}" | Move-Item -Force -Destination "{{ archive.base_destination_directory }}"
  when: archive.move_and_delete_base_directory is defined and extract_command_status.rc is defined and extract_command_status.rc == 0

- name: Remove base directory
  win_file:
    path: "{{ archive.base_destination_directory }}\\{{ archive.move_and_delete_base_directory }}"
    state: absent
  when: archive.move_and_delete_base_directory is defined and extract_command_status.rc is defined and extract_command_status.rc == 0

- name: Write archiveextracted file
  win_copy:
    dest: "D:\\artifactory-archives\\{{ archive.filename }}.archiveextracted"
    content: "{{ remote_archive_head.x_checksum_sha256 }}"
  when: extract_command_status.rc is defined and extract_command_status.rc == 0

- name: Delete the archive if the archiveextracted file is there and sha256 is correct or if the extration command was successful
  win_file:
    path: "D:\\artifactory-archives\\{{ archive.filename }}"
    state: absent
  when: (archiveextracted.stat.exists and remote_archive_head.x_checksum_sha256 in archiveextracted_sha256.content|b64decode) or (extract_command_status.rc is defined and extract_command_status.rc == 0)
