---
- name: Ensure artifactory status archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_status_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure artifactory downloads archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_downloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure artifactory tempdownloads archives directory is present
  ansible.builtin.file:
    path: "{{ artifactory_tempdownloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Add required packages
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: present
  become: true

- name: Install JFrog cli
  ansible.builtin.get_url:
    url: https://releases.jfrog.io/artifactory/jfrog-cli/v1/[RELEASE]/jfrog-cli-linux-amd64/jfrog
    dest: /usr/bin/jfrog
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Get and expand archives
  ansible.builtin.include_tasks: expand_archive_posix.yml
  loop: "{{ archive_definitions }}"
  loop_control:
    loop_var: archive
