- name: Check destination directories and ensure they are present
  vars:
    destination_directories: "{{ archives | map(attribute='base_destination_directory') | list }}"
  block:
    - name: "Check if destination directories are present"
      ansible.builtin.stat:
        path: "{{ item }}"
      register: directory_stats
      loop: "{{ destination_directories }}"

    - name: "Ensure destination directories are present"
      ansible.builtin.file:
        path: "{{ item.item }}"
        state: directory
        owner: "{{ ansible_user }}"
        mode: "0755"
      when: not item.stat.exists or not item.stat.isdir
      loop: "{{ directory_stats.results }}"

- name: Manage archive files
  vars:
    archive_loop_var: archive
  loop: "{{ archives }}"
  loop_control:
    loop_var: "{{ archive_loop_var }}"
  block:
    - name: "{{ archive_loop_var.filename }}: Check sha256 file is present"
      ansible.builtin.stat:
        path: "{{ artifactory_status_directory }}/{{ archive_loop_var.filename }}.sha256"
      register: downloaded_sha256_file

    - name: "{{ archive_loop_var.filename }}: Read sha256 from downloaded_sha256_file file if present"
      ansible.builtin.slurp:
        src: "{{ artifactory_status_directory }}/{{ archive_loop_var.filename }}.sha256"
      register: downloaded_sha256_file_sha256
      when: downloaded_sha256_file.stat.exists

    - name: "{{ archive_loop_var.filename }}: Perform a HEAD on the remote file to read sha256"
      ansible.builtin.uri:
        url: "{{ artifactory_base_url }}/{{ archive_loop_var.artifactory_path }}/{{archive_loop_var.filename }}"
        method: HEAD
        timeout: 60
        url_username: "{{ ansible_deployment_artifactory_user }}"
        url_password: "{{ ansible_deployment_artifactory_key }}"
      register: remote_archive_head

    - name: "{{ archive_loop_var.filename }}: Check downloaded file is present"
      ansible.builtin.stat:
        path: "{{ artifactory_status_directory }}/{{ archive_loop_var.filename }}"
      register: downloaded_file

    - name: "{{ archive_loop_var.filename }}: Delete the downloaded archive if the size is different"
      ansible.builtin.file:
        path: "{{ artifactory_downloads_directory }}/{{ archive_loop_var.filename }}"
        state: absent
      when: downloaded_file.stat.exists and remote_archive_head.content_length !=downloaded_file.stat.size
