---
- name: Ensure artifactory status archives directory is present
  win_file:
    path: "{{ artifactory_status_directory }}"
    state: directory

- name: Ensure artifactory downloads archives directory is present
  win_file:
    path: "{{ artifactory_downloads_directory }}"
    state: directory

- name: Ensure artifactory tempdownloads archives directory is present
  win_file:
    path: "{{ artifactory_tempdownloads_directory }}"
    state: directory

- name: Install required tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ required_packages }}"
  become: true

- ansible.builtin.inlude_tasks: expand_archive_windows.yml
  loop: "{{ archive_definitions }}"
  loop_control:
    loop_var: archive
