---
- hosts: all
  gather_facts: true
  tasks:
    - name: Read platform-specific variables
      include_vars: "{{ varfile }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
            - "{{ ansible_system }}.yml"
          skip: true
      loop_control:
        loop_var: varfile

    - name: Connect package managers to CCDC resources
      ansible.builtin.include_role:
        name: ccdc.package_manager_configuration

    - name: Expand archives
      ansible.builtin.include_role:
        name: ccdc.expand_artifactory_archives
      vars:
        archive_definitions: "{{ artifactory_archives }}"
